### Mata Kuliah Intelegensi Buatan
### Tugas Kecil 2 - Eksplokrasi scikit-learn pada Jupyter Notebook

#### Membaca dataset standar iris dan dataset play-tennis (dataset eksternal dalam format csv).  

In [3]:
from sklearn import datasets
import pandas as pd

# Membaca data set standar iris dari sklearn
iris = datasets.load_iris()

# membaca data csv play tennis
weather = pd.read_csv('weather.nominal.csv')

#### Melakukan pembelajaran Naive Bayes, Decision Tree, k-Nearest Neighbor, Artificial Neural Network (Multilayer Perceptron) untuk dataset iris dengan skema full-training, dan menampilkan modelnya.

In [14]:
# Pembelajaran Fullset Training
# Naive Bayes
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb_pred = gnb.fit(iris.data, iris.target)
print("Model Naive Bayes :")
print(gnb_pred.__dict__)
print()

# Decision Tree
from sklearn import tree
clf = tree.DecisionTreeClassifier()
dt_pred = clf.fit(iris.data, iris.target) 
print("Model Decision Tree :")
print(dt_pred.__dict__)
print()

# k-NN
from sklearn.neighbors.nearest_centroid import NearestCentroid
import numpy as np
clf = NearestCentroid()
knn_pred = clf.fit(iris.data, iris.target)
print("Metode pembelajaran k-NN : ")
print(knn_pred.__dict__)
print()

# Artificial Neural Network
from sklearn.neural_network import MLPClassifier
ann = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(10, 5), random_state=1)

ann_pred = ann.fit(iris.data, iris.target)
print("Model ANN MLP : ")
print(ann_pred.__dict__)

Model Naive Bayes :
{'priors': None, 'var_smoothing': 1e-09, 'epsilon_': 3.0955026666666677e-09, 'classes_': array([0, 1, 2]), 'theta_': array([[5.006, 3.428, 1.462, 0.246],
       [5.936, 2.77 , 4.26 , 1.326],
       [6.588, 2.974, 5.552, 2.026]]), 'sigma_': array([[0.121764, 0.140816, 0.029556, 0.010884],
       [0.261104, 0.0965  , 0.2164  , 0.038324],
       [0.396256, 0.101924, 0.298496, 0.073924]]), 'class_count_': array([50., 50., 50.]), 'class_prior_': array([0.33333333, 0.33333333, 0.33333333])}

Model Decision Tree :
{'criterion': 'gini', 'splitter': 'best', 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'min_weight_fraction_leaf': 0.0, 'max_features': None, 'random_state': None, 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_impurity_split': None, 'class_weight': None, 'presort': False, 'n_features_': 4, 'n_outputs_': 1, 'classes_': array([0, 1, 2]), 'n_classes_': 3, 'max_features_': 4, 'tree_': <sklearn.tree._tree.Tree object at 0x0000023B72AE

#### Melakukan pembelajaran NaïveBayes, DecisionTree, kNN, dan MLP untuk dataset iris dengan skema split train 90% dan test 10%, dan menampilkan kinerja serta confusion matrixnya.

In [5]:
# Pembelajaran 90% training 10% test
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

train_data, test_data, train_target, test_target = train_test_split(
    iris.data, iris.target, test_size=0.1, random_state=0)

# Naive Bayes
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb_pred = gnb.fit(train_data, train_target).predict(test_data)
accuracy = (test_target == gnb_pred).sum()/len(test_data)*100
print("Akurasi model naive bayes : %d persen" % (accuracy))
print("Confusion Matrix :")
print(confusion_matrix(test_target, gnb_pred))
print()

# Decision Tree
from sklearn import tree
clf = tree.DecisionTreeClassifier()
dt_pred = clf.fit(train_data, train_target).predict(test_data)
accuracy = (dt_pred == test_target).sum()/len(test_data)*100
print("Akurasi model decision tree : %d persen" % (accuracy))
print("Confusion Matrix :")
print(confusion_matrix(test_target, dt_pred))
print()

# k-NN
from sklearn.neighbors.nearest_centroid import NearestCentroid
import numpy as np
clf = NearestCentroid()
knn = clf.fit(train_data, train_target)
knn_pred = knn.predict(test_data)
accuracy = (test_target == knn_pred).sum()/len(test_data)*100
print("Akurasi kNN : %d persen" % (accuracy))
print("Confusion Matrix :")
print(confusion_matrix(test_target, knn_pred))
print()

# Artificial Neural Network
from sklearn.neural_network import MLPClassifier
ann = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(10, 5), random_state=1)

ann_pred = ann.fit(train_data, train_target).predict(test_data)
accuracy = (test_target == ann_pred).sum()/len(test_data)*100
print("Akurasi ANN : %d persen" % (accuracy))
print("Confusion Matrix :")
print(confusion_matrix(test_target, ann_pred))

Akurasi model naive bayes : 93 persen
Confusion Matrix :
[[3 0 0]
 [0 8 0]
 [0 1 3]]

Akurasi model decision tree : 100 persen
Confusion Matrix :
[[3 0 0]
 [0 8 0]
 [0 0 4]]

Akurasi kNN : 86 persen
Confusion Matrix :
[[3 0 0]
 [0 6 2]
 [0 0 4]]

Akurasi ANN : 100 persen
Confusion Matrix :
[[3 0 0]
 [0 8 0]
 [0 0 4]]


#### Melakukan pembelajaran NaïveBayes, DecisionTree, kNN, dan MLP untuk dataset iris dengan skema 10-fold cross validation, dan menampilkan kinerjanya.

In [6]:
# Pembelajaran dengan skema 10-fold cross validation
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score

# Naive Bayes
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb_pred = gnb.fit(train_data, train_target)
scores = cross_val_score(gnb_pred, iris.data, iris.target, cv=10)
print("Akurasi model naive bayes : %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
print()

# Decision Tree
from sklearn import tree
clf = tree.DecisionTreeClassifier()
dt_pred = clf.fit(train_data, train_target)
scores = cross_val_score(dt_pred, iris.data, iris.target, cv=10)
print("Akurasi model decision tree : %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
print()

# k-NN
from sklearn.neighbors.nearest_centroid import NearestCentroid
import numpy as np
clf = NearestCentroid()
knn_pred = clf.fit(train_data, train_target)
scores = cross_val_score(knn_pred, iris.data, iris.target, cv=10)
print("Akurasi k-NN : %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
print()

# Artificial Neural Network
from sklearn.neural_network import MLPClassifier
ann = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(10, 5), random_state=1)

ann_pred = ann.fit(train_data, train_target)
scores = cross_val_score(ann_pred, iris.data, iris.target, cv=10)
print("Akurasi model ANN : %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Akurasi model naive bayes : 0.95 (+/- 0.09)

Akurasi model decision tree : 0.96 (+/- 0.09)

Akurasi k-NN : 0.93 (+/- 0.12)

Akurasi model ANN : 0.98 (+/- 0.06)


#### Menyimpan (save) model/hipotesis hasil pembelajaran ke sebuah file eksternal

In [7]:
from sklearn.externals import joblib
joblib.dump(gnb_pred, 'gnb-iris.joblib') 
joblib.dump(dt_pred, 'dt-iris.joblib') 
joblib.dump(knn_pred, 'knn-iris.joblib') 
joblib.dump(ann_pred, 'ann-iris.joblib') 

['ann-iris.joblib']

#### Membaca (read)model/hipotesis dari file eksternal, membuat instance baru, dan melakukan prediksi terhadap instance tersebut.

In [8]:
gnbLoad = joblib.load('gnb-iris.joblib') 
dtLoad = joblib.load('dt-iris.joblib') 
knnLoad = joblib.load('knn-iris.joblib') 
annLoad = joblib.load('ann-iris.joblib') 

In [9]:
# g. membuat instance baru dengan memberi nilai untuk setiap atribut
newInstance = np.array([[6.0, 3.3, 6.1, 2.6]])

# h. Melakukan klasifikasi dengan memanfaatkan model/hipotesisNaïveBayes, DecisionTree, dan kNN dan instance pada g.
print("Klasifikasi dengan Naive Bayes : %d" % gnbLoad.predict(newInstance))
print("Klasifikasi dengan Decision Tree : %d" % dtLoad.predict(newInstance))
print("Klasifikasi dengan kNN : %d" % knnLoad.predict(newInstance))
print("Klasifikasi dengan ANN MLP : %d" % annLoad.predict(newInstance))

Klasifikasi dengan Naive Bayes : 2
Klasifikasi dengan Decision Tree : 2
Klasifikasi dengan kNN : 2
Klasifikasi dengan ANN MLP : 2
